package envfile

import (
	"strings"
	"testing"
)

func TestQuote(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want string
	}{
		{"plain", "production", "production"},
		{"url stays bare", "postgres://host:5432/db", "postgres://host:5432/db"},
		{"empty is quoted", "", `""`},
		{"space forces quotes", "hello world", `"hello world"`},
		{"double quote escaped", `say "hi"`, `"say \"hi\""`},
		{"backslash escaped", `a\b`, `"a\\b"`},
		{"dollar escaped so parsers do not expand it", "$HOME", `"\$HOME"`},
		{"backtick escaped", "a`b`", "\"a\\`b\\`\""},
		{"newline escaped", "a\nb", `"a\nb"`},
		{"tab escaped", "a\tb", `"a\tb"`},
		// The two characters whose quoting is load-bearing for other people's
		// parsers rather than for ours: unquoted, a # opens a comment and an =
		// makes the rest of the line ambiguous. They fall out of needsQuoting's
		// allow-list rather than being handled by name, so they are exactly the
		// cases that would regress silently the next time that list is edited.
		{"hash forces quotes", "#foo", `"#foo"`},
		{"hash mid-value forces quotes", "a#b", `"a#b"`},
		{"equals forces quotes", "a=b", `"a=b"`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Quote(tt.in); got != tt.want {
				t.Errorf("Quote(%q) = %s, want %s", tt.in, got, tt.want)
			}
		})
	}
}

func TestRender(t *testing.T) {
	vals := map[string]string{"NODE_ENV": "production", "GREETING": "hello world"}
	got := Render([]string{"GREETING", "NODE_ENV"}, func(k string) string { return vals[k] }, "")

	want := "GREETING=\"hello world\"\nNODE_ENV=production\n"
	if got != want {
		t.Errorf("Render() = %q, want %q", got, want)
	}
}

func TestRenderHeader(t *testing.T) {
	got := Render(nil, nil, "generated by pklenv\ndo not edit")
	if !strings.HasPrefix(got, "# generated by pklenv\n# do not edit\n\n") {
		t.Errorf("Render() header = %q", got)
	}
}

func TestValidateName(t *testing.T) {
	valid := []string{"NODE_ENV", "_private", "A1", "lower_case"}
	for _, n := range valid {
		if err := ValidateName(n); err != nil {
			t.Errorf("ValidateName(%q) = %v, want nil", n, err)
		}
	}

	invalid := []string{"", "1LEADING", "has-dash", "has space", "has.dot"}
	for _, n := range invalid {
		if err := ValidateName(n); err == nil {
			t.Errorf("ValidateName(%q) = nil, want an error", n)
		}
	}
}
