// Package schema keeps each config directory supplied with the PklEnv module
// its configs amend.
//
// The module ships inside the pklenv binary, and a copy is written next to the
// configs so that a config can say `amends "env-schema.pkl"` — a plain relative
// path that pklenv, `pkl eval` and the editor all resolve identically, without
// a network fetch. The copy is meant to be committed: it is code that runs at
// evaluation time, so a change to it should arrive as a reviewable diff rather
// than appear silently in someone's working tree.
package schema

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/idleberg/pklenv"
)

// Filename is the name of the vendored copy.
//
// Deliberately not matching config.Discover's env.pkl / env.*.pkl glob: the
// prefix here is "env-", not "env.", so discovery skips it. A generic name like
// schema.pkl was rejected for a different reason — this file is rewritten
// automatically, and a name that collides with something a user already has
// turns that into data loss.
const Filename = "env-schema.pkl"

// marker identifies a copy pklenv wrote.
//
// It carries no version number on purpose. A version in the header would change
// the file's contents on every pklenv release even when the schema itself is
// untouched, which would turn "verify and refresh" into a source of diffs that
// mean nothing.
const marker = "generated by pklenv"

const header = `// ` + marker + `; do not edit.
//
// This is the module your env.pkl amends, vendored from the pklenv binary so
// that evaluation needs no network access. Commit it: it is executed whenever a
// config is evaluated, so changes to it belong in review.
//
// To extend the schema, amend it from a module of your own rather than editing
// this file — pklenv rewrites it whenever it differs from the version built
// into the binary.

`

// Outcome describes what Ensure did, for the caller to report.
type Outcome int

const (
	// Unchanged covers both "already current" and "not wanted here". It is the
	// CI case: the committed copy matches, and nothing is written.
	Unchanged Outcome = iota

	// Written means the file was absent and has been created.
	Written

	// Refreshed means an out-of-date copy was replaced. Worth telling the user
	// about, since it leaves their working tree dirty.
	Refreshed

	// Stale means the copy is out of date and could not be replaced, because the
	// directory is not writable. Evaluation continues with what is there.
	Stale
)

// ErrForeign reports a file that pklenv did not write.
//
// Refusing is the only safe answer: Ensure overwrites without asking, so a name
// collision with a file somebody else authored would be silent data loss.
var ErrForeign = errors.New("exists but was not generated by pklenv")

// Ensure makes sure the directory holding configPath has a current copy.
//
// The copy is created only when this config asks for it by name, so pklenv does
// not scatter files through directories that never referenced one. An existing
// copy is verified regardless of whether this particular config mentions it —
// a config that amends another config which amends the schema never names it
// directly, and a stale copy in that arrangement is still worth correcting.
//
// Verifying rather than merely creating-when-absent is the point: the schema
// runs at evaluation time, so a locally modified copy would otherwise be
// trusted inside the very boundary the permission flags draw.
func Ensure(configPath string) (Outcome, error) {
	dir := filepath.Dir(configPath)
	target := filepath.Join(dir, Filename)
	want := header + pklenv.Schema

	existing, err := os.ReadFile(target)
	switch {
	case err == nil:
		if !strings.Contains(string(existing), marker) {
			return Unchanged, fmt.Errorf("%s %w", target, ErrForeign)
		}
		if string(existing) == want {
			return Unchanged, nil
		}
		if err := write(target, want); err != nil {
			// Out of date but readable: an old schema is more likely to evaluate
			// than no schema at all, so a read-only checkout keeps working and
			// the caller warns instead.
			return Stale, nil
		}
		return Refreshed, nil

	case errors.Is(err, os.ErrNotExist):
		referenced, refErr := references(configPath)
		if refErr != nil || !referenced {
			return Unchanged, nil
		}
		if err := write(target, want); err != nil {
			return Unchanged, fmt.Errorf("writing %s: %w", target, err)
		}
		return Written, nil

	default:
		return Unchanged, fmt.Errorf("reading %s: %w", target, err)
	}
}

// write replaces the file atomically, so a crash or a full disk cannot leave a
// half-written module that fails to parse on the next run.
func write(target, content string) error {
	tmp, err := os.CreateTemp(filepath.Dir(target), "."+Filename+".*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(name) // no-op once the rename has succeeded
	}()

	if _, err := tmp.WriteString(content); err != nil {
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	// 0644, unlike the 0600 that .env files get: this is a schema, it holds no
	// values, and it is meant to be committed and read.
	if err := os.Chmod(name, 0o644); err != nil {
		return err
	}
	return os.Rename(name, target)
}

// references reports whether the config names the vendored schema.
//
// A plain substring test over the source. Parsing Pkl to answer this would mean
// evaluating it, which is the thing that cannot happen until the schema is in
// place, so the question has to be answered from the text.
func references(configPath string) (bool, error) {
	src, err := os.ReadFile(configPath)
	if err != nil {
		return false, err
	}
	return strings.Contains(string(src), Filename), nil
}
